### ISSUE TITLE
Updating to 0.8 breaks app

### ISSUE THREAD

**Issue by AsavarTzeth** [owncloud/tasks#265]
### Steps to reproduce
1. Navigate to the integrated application management
2. Update from previous version to current one (0.8)
3. Launch the app

### Expected behaviour
The app launches when clicked

### Actual behaviour
I get a white page and nothing else

### Server configuration
**Operating system**:
Ubuntu 15.04

**Web server:**
nginx 1.6.2-5ubuntu3.1

**Database:**
postgresql 9.4.4-0ubuntu0.15.04

**PHP version:**
php-fpm 5.6.4+dfsg-4ubuntu6.2

**ownCloud version:** (see ownCloud admin page)
ownCloud 8.1.1 (stable)

**Updated from an older ownCloud or fresh install:**
updated

**List of activated apps:**

```
Enabled:
 - activity: 2.0.1
 - bookmarks: 0.4
 - calendar: 0.7.3
 - contacts: 0.4.0.0
 - documents: 0.10.2
 - files: 1.1.10
 - files_external: 0.2.3
 - files_locking: 
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - galleryplus: 13.0.0
 - music: 0.3.7
 - news: 6.0.3
 - provisioning_api: 0.2
 - tasks: 0.8
 - templateeditor: 0.1
Disabled:
 - encryption
 - external
 - gallery
 - music.old
 - ownnote
 - storagecharts2
 - user_external
 - user_ldap
 - user_webdavauth
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'trusted_domains' => 
  array (
    0 => 'cloud.hembas.se',
  ),
  'datadirectory' => '/volume1/owncloud',
  'overwrite.cli.url' => 'https://cloud.hembas.se',
  'dbtype' => 'pgsql',
  'version' => '8.1.1.3',
  'dbpassword' => '',
  'dbhost' => '/var/run/postgresql',
  'dbtableprefix' => 'oc_',
  'installed' => 'true',
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'mail_domain' => 'cloud.hembas.se',
  'mail_smtpmode' => 'php',
  'mail_from_address' => 'info',
  'theme' => '',
  'maintenance' => false,
  'loglevel' => 2,
  'appstoreenabled' => true,
  'appstoreurl' => 'https://api.owncloud.com/v1',
  'logfile' => '/var/log/nginx/owncloud.log',
  'logtimezone' => 'Europe/Stockholm',
  'asset-pipeline.enabled' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
local

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** 
no

### Client configuration
**Browser:**
Chromium 45.0.2454.85 (64-bit)

**Operating system:**
Arch Linux

#### Web server error log
error.log
```
2015/09/10 10:02:34 [error] 15592#0: *81913 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to a member function getUID() on null in /var/www/owncloud/apps/tasks/appinfo/application.php on line 124" while reading response header from upstream, client: 79.138.130.2, server: cloud.hembas.se, request: "GET /index.php/apps/tasks/lists HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "cloud.hembas.se", referrer: "https://cloud.hembas.se/index.php/apps/tasks/"
2015/09/11 13:08:35 [error] 15594#0: *103897 open() "/var/www/owncloud/favicon.ico" failed (2: No such file or directory), client: 95.195.141.221, server: cloud.hembas.se, request: "GET /favicon.ico HTTP/1.1", host: "cloud.hembas.se", referrer: "https://cloud.hembas.se/index.php/apps/tasks/"
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"Ccm6Atc8s\/pf9J5qo7I8","remoteAddr":"x.x.x.x","app":"PHP","message":"vsprintf(): Too few arguments at \/var\/www\/owncloud\/lib\/private\/l10n\/string.php#76","level":3,"time":"2015-09-11T14:35:34+02:00"}
{"reqId":"Ccm6Atc8s\/pf9J5qo7I8","remoteAddr":"x.x.x.x","app":"PHP","message":"Method OC_L10N_String::__toString() must return a string value at \/var\/www\/owncloud\/lib\/private\/util.php#1106","level":3,"time":"2015-09-11T14:35:34+02:00"}
{"reqId":"PG49GwTuLYwbJS8hiZJn","remoteAddr":"x.x.x.x","app":"tasks","message":"Could not find resource file \"\/apps\/tasks\/js\/vendor\/appframework\/app.js\"","level":3,"time":"2015-09-11T14:35:52+02:00"}
{"reqId":"PG49GwTuLYwbJS8hiZJn","remoteAddr":"x.x.x.x","app":"index","message":"Exception: {\"Exception\":\"RuntimeException\",\"Message\":\"The source file \\\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/tasks\\\/js\\\/vendor\\\/appframework\\\/app.js\\\" does not exist.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/kriswallsmith\\\/assetic\\\/src\\\/Assetic\\\/Asset\\\/BaseAsset.php(103): Assetic\\\\Asset\\\\FileAsset->load()\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/kriswallsmith\\\/assetic\\\/src\\\/Assetic\\\/Asset\\\/AssetCollection.php(151): Assetic\\\\Asset\\\\BaseAsset->dump(NULL)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/kriswallsmith\\\/assetic\\\/src\\\/Assetic\\\/AssetWriter.php(68): Assetic\\\\Asset\\\\AssetCollection->dump()\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/templatelayout.php(231): Assetic\\\\AssetWriter->writeAsset(Object(Assetic\\\\Asset\\\\AssetCollection))\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/templatelayout.php(147): OC_TemplateLayout->generateAssets()\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/template.php(128): OC_TemplateLayout->__construct('user', 'tasks')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/appframework\\\/http\\\/templateresponse.php(156): OC_Template->fetchPage()\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(112): OCP\\\\AppFramework\\\\Http\\\\TemplateResponse->render()\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(108): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Tasks\\\\Controller\\\\PageController), 'index')\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('PageController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#10 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(274): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(873): OC\\\\Route\\\\Router->match('\\\/apps\\\/tasks\\\/')\\n#13 \\\/var\\\/www\\\/owncloud\\\/index.php(40): OC::handleRequest()\\n#14 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/kriswallsmith\\\/assetic\\\/src\\\/Assetic\\\/Asset\\\/FileAsset.php\",\"Line\":62}","level":4,"time":"2015-09-11T14:35:54+02:00"}
{"reqId":"PG49GwTuLYwbJS8hiZJn","remoteAddr":"x.x.x.x","app":"tasks","message":"Could not find resource file \"\/apps\/tasks\/js\/vendor\/appframework\/app.js\"","level":3,"time":"2015-09-11T14:35:54+02:00"}
{"reqId":"PG49GwTuLYwbJS8hiZJn","remoteAddr":"x.x.x.x","app":"PHP","message":"RuntimeException: The source file \"\/var\/www\/owncloud\/apps\/tasks\/js\/vendor\/appframework\/app.js\" does not exist. at \/var\/www\/owncloud\/3rdparty\/kriswallsmith\/assetic\/src\/Assetic\/Asset\/FileAsset.php#62","level":3,"time":"2015-09-11T14:35:56+02:00"}
```

#### Browser log
Not sure how to do this

**Comment by raimund-schluessler** [comment]
Your webserver error log is very weird. In ```/var/www/owncloud/apps/tasks/appinfo/application.php on line 124``` there is no such function ```getUID()``` in version 0.8 of the app. However, it was there in v0.7.1

Also, following your ownCloud log, the app tries to load ```\/apps\/tasks\/js\/vendor\/appframework\/app.js``` which is also not there anymore in v0.8, but was in 0.7.1.

So it looks like some parts of your app were updated an others were not. Please make sure your app directory is writable for the webserver. However, I think in order to restore the proper functioning, you need to deactivate and delete the app and reinstall it again.

**Comment by AsavarTzeth** [comment]
I already tried reinstalling it, but just to be sure I did it again. No difference. The app always had write access.

I do agree that something is weird though. My server may be high-end but a fresh install/update is done in less than a second. That makes me believe it does not download the new version for some reason.

**Comment by raimund-schluessler** [comment]
Did you really delete it on the filesystem? Or just deactivated it in the appmanager?

**Comment by AsavarTzeth** [comment]
Well I did uninstall it in the app manager, not just deactivate it. I also made sure to look in the directory via ssh as well and it was indeed deleted.

**Comment by raimund-schluessler** [comment]
Can you check if the correct files are downloaded to your server, e.g. by comparing some files on your server via SSH to the ones hosted in the current master here? And maybe there is some caching going on? Can you try reloading your webbrowser and restarting your webserver?

**Comment by AsavarTzeth** [comment]
I do have APCu caching enabled.

Ok deleting the app, then restarting both php-fpm and nginx did the job. It now works. I wonder if this might be the cause of the news app breaking for me the same way.

**Comment by raimund-schluessler** [comment]
Weird behavior. I also have APCu enabled, but I do all upgrades via ```php occ upgrade``` on the command line with stopping the webserver (apache in this case) before. I can't tell how it behaves with automatically updating via the app manager.

Anyway, good it does work now.

**Comment by AsavarTzeth** [comment]
Yeah I have been thinking of doing upgrades the same way as you. However, I do see some value in discovering this. Not all people have shell access, nor are all people even familiar with the shell.

By the way, I fixed the news app the same way. So a great thanks for your quick support!
